### Raiz da aplicação

GET http://localhost:5056/

### Listagem de produtos

GET http://localhost:5056/produto/listar

### Busca de produtos por nome

GET http://localhost:5056/produto/buscar/Arroz

### Cadastro de produtos

POST http://localhost:5056/produto/cadastrar

### Obter cadastro

GET http://localhost:5056/produto/cadastrar/42