### Raiz da aplicação

GET http://localhost:5056/

### Listagem de produtos

GET http://localhost:5056/produto/listar

### Cadastro de produtos

POST http://localhost:5056/produto/cadastrar

### Obter cadastro

GET http://localhost:5056/produto/cadastrar/42