### Raiz da aplicação

GET http://localhost:5056/

### Listagem de produtos

GET http://localhost:5056/produto/listar

### Busca de produtos por nome

GET http://localhost:5056/produto/buscar/Arroz

### Cadastro de produtos

POST http://localhost:5056/produto/cadastrar

### Obter cadastro pela url

GET http://localhost:5056/produto/cadastrar/Alface/500g/12

### cadastrar produto pelo corpo

POST http://localhost:5056/produto/cadastrar/
Content-Type: application/json

{
    "nome": "pizza",
    "descricao": "Caixa de pizza media",
    "valor": 35.60
}


### alterar produto
PUT http://localhost:5056/produto/atualizar/Arroz
Content-Type: application/json

{
    "nome": "carne",
    "descricao": "1kg de carne",
    "valor": 39.40
}

### Deleta o produto
DELETE http://localhost:5056/produto/deletar/Arroz


### Altera parcialmente o produto

PATCH http://localhost:5056/produto/patch/feijao/descricao
Content-Type: application/json

{
    "descricao": "Saco de feijao 6kg"
}
